version: '2.1'

services:

  spark-master:
    hostname: spark-master
    container_name: spark-master
    image: spark-cluster:0.02
    restart: always
    ports:
      - 18080:18080 # 스파크 웹 UI
    stdin_open: true
    tty: true
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=17077
      - SPARK_MASTER_WEBUI_PORT=18080

  # spark-slave-1:
  #   hostname: spark-slave-1
  #   container_name: spark-slave-1
  #   image: spark-cluster:0.01
  #   restart: always
  #   mem_limit: "4g"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - SparkMode=slave
  #     - SparkSlaveCore=4
  #     - SparkSlaveMemory=4g
  #   depends_on:
  #     - spark-master

  # spark-slave-2:
  #   hostname: spark-slave-2
  #   container_name: spark-slave-2
  #   image: spark-cluster:0.01
  #   restart: always
  #   mem_limit: "4g"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - SparkMode=slave
  #     - SparkSlaveCore=2
  #     - SparkSlaveMemory=4g
  #   depends_on:
  #     - spark-master

  # spark-slave-3:
  #   hostname: spark-slave-3
  #   container_name: spark-slave-3
  #   image: spark-cluster:0.01
  #   restart: always
  #   mem_limit: "4g"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     - SparkMode=slave
  #     - SparkSlaveCore=4
  #     - SparkSlaveMemory=2g
  #   depends_on:
  #     - spark-master